clear; clc;
mpc.version = '2';
mpc.baseMVA = 100;

% اطلاعات باس ها
% [bus_i type Pd Qd Gs Bs area Vm Va baseKV zone Vmax Vmin]
mpc.bus = [
    1   3   0     0    0  0  1  1.04  0  138  1  1.1  0.9;
    2   2   0     0    0  0  1  1.04  0  138  1  1.1  0.9;
    3   1   100   50   0  0  1  1.00  0  138  1  1.1  0.9;
    4   1   30    10   0  0  1  1.00  0  138  1  1.1  0.9;
];

% اطلاعات ژنراتورها (بدون محدودیت Q)
% [bus Pg Qg Qmax Qmin Vg mBase status Pmax Pmin]
mpc.gen = [
    1   0   0   9999  -9999  1.04  100  1  9999  -9999; % Slack
    2   50  0   9999  -9999  1.04  100  1  9999  -9999; % Gen 2
];

% اطلاعات خطوط
% [fbus tbus r x b rateA rateB rateC ratio angle status angmin angmax]
mpc.branch = [
    1   2   0  0.20   0  0  0  0  0  0  1  -360  360;
    1   3   0  0.40   0  0  0  0  0  0  1  -360  360;
    2   3   0  0.50   0  0  0  0  0  0  1  -360  360;
    2   4   0  0.50   0  0  0  0  0  0  1  -360  360;
    3   4   0  0.25   0  0  0  0  0  0  1  -360  360;
];

disp('===================================================');
disp('   PART A: Power Flow WITHOUT Q Limits on Gen 2    ');
disp('===================================================');

% اجرای پخش بار
results_A = runpf(mpc);
V2_A = results_A.bus(2, 8); 
Qg2_A = results_A.gen(2, 3); 

fprintf('\n>>> RESULTS FOR PART A <<<\n');
fprintf('Voltage at Bus 2: %.4f pu\n', V2_A);
fprintf('Reactive Power Generated by Gen 2: %.4f MVAR (%.4f pu)\n\n', Qg2_A, Qg2_A/mpc.baseMVA);